name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    # every day
    - cron: 00 4 * * *
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  BASE_REPO: ${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------------
      # Build + push latest package
      # -------------------------------
      - name: Extract metadata for latest image
        id: meta_latest
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.BASE_REPO }}
          tags: |
            type=raw,value=latest
            type=schedule,pattern={{date 'YYYYMMDD-HHmmss' tz='Europe/Berlin'}}
            type=ref,event=branch

      - name: Build and push Latest Docker image
        id: push_latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta_latest.outputs.tags }}
          labels: ${{ steps.meta_latest.outputs.labels }}
          build-args: |
            BASE_IMAGE=ghcr.io/cosmian/kms:latest

      # -------------------------------
      # Build + push dev package
      # -------------------------------
      - name: Extract metadata for dev image
        id: meta_dev
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.BASE_REPO }}-dev
          tags: |
            type=raw,value=develop
            type=schedule,pattern={{date 'YYYYMMDD-HHmmss' tz='Europe/Berlin'}}

      - name: Build and push Dev Docker image
        id: push_dev
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta_dev.outputs.tags }}
          labels: ${{ steps.meta_dev.outputs.labels }}
          build-args: |
            BASE_IMAGE=ghcr.io/cosmian/kms:develop

      # -------------------------------
      # Build + push SG-O dev package
      # -------------------------------
      - name: Extract metadata for SG-O image
        id: meta_sg_o
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.BASE_REPO }}-sg-o
          tags: |
            type=raw,value=develop
            type=schedule,pattern={{date 'YYYYMMDD-HHmmss' tz='Europe/Berlin'}}

      - name: Build and push SG-O Docker image
        id: push_sg_o
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta_sg_o.outputs.tags }}
          labels: ${{ steps.meta_sg_o.outputs.labels }}
          build-args: |
            BASE_IMAGE=ghcr.io/sg-o/kms:develop

      # -------------------------------
      # Attestation (for Latest image)
      # -------------------------------
      - name: Generate artifact attestation for latest image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.BASE_REPO }}
          subject-digest: ${{ steps.push_latest.outputs.digest }}
          push-to-registry: true
